"""add_missing_fields

Revision ID: 20c364b0fb81
Revises: 3f5806bee441
Create Date: 2026-05-01 12:22:43.820649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20c364b0fb81'
down_revision: Union[str, None] = '3f5806bee441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foodlog', 'meal_slot',
               existing_type=postgresql.ENUM('Breakfast', 'Lunch', 'Dinner', 'Snack', 'PreWorkout', 'PostWorkout', name='mealslot'),
               nullable=True)
    op.add_column('healthmetric', sa.Column('sleep_score', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('llm_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('llm_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('telegram_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('telegram_chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('bmr_override', sa.Float(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'sex',
               existing_type=postgresql.ENUM('M', 'F', 'Other', name='sexenum'),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('usergoal', 'direction',
               existing_type=postgresql.ENUM('lose', 'maintain', 'gain', name='goaldirection'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usergoal', 'direction',
               existing_type=postgresql.ENUM('lose', 'maintain', 'gain', name='goaldirection'),
               nullable=False)
    op.alter_column('user', 'is_totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'sex',
               existing_type=postgresql.ENUM('M', 'F', 'Other', name='sexenum'),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'bmr_override')
    op.drop_column('user', 'telegram_chat_id')
    op.drop_column('user', 'telegram_username')
    op.drop_column('user', 'llm_provider')
    op.drop_column('user', 'llm_api_key')
    op.drop_column('healthmetric', 'sleep_score')
    op.alter_column('foodlog', 'meal_slot',
               existing_type=postgresql.ENUM('Breakfast', 'Lunch', 'Dinner', 'Snack', 'PreWorkout', 'PostWorkout', name='mealslot'),
               nullable=False)
    # ### end Alembic commands ###
