"""add_endurance_module

Revision ID: 3f5806bee441
Revises: f41781e3913b
Create Date: 2026-04-30 20:20:53.870246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f5806bee441'
down_revision: Union[str, None] = 'f41781e3913b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endurancegoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_event_kj', sa.Float(), nullable=False),
    sa.Column('hardest_section_power', sa.Float(), nullable=False),
    sa.Column('hardest_section_duration_min', sa.Float(), nullable=False),
    sa.Column('sprint_capability_sec', sa.Integer(), nullable=False),
    sa.Column('recovery_demand', sa.Enum('Low', 'Average', 'High', name='recoverydemand'), nullable=True),
    sa.Column('ramp_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('userphysiology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lt1_power', sa.Float(), nullable=False),
    sa.Column('lt2_power', sa.Float(), nullable=False),
    sa.Column('max_sprint_duration_sec', sa.Integer(), nullable=False),
    sa.Column('last_calibrated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('weeklyplanner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('ltw_kj', sa.Float(), nullable=False),
    sa.Column('stw_kj', sa.Float(), nullable=False),
    sa.Column('target_volume_kj', sa.Float(), nullable=False),
    sa.Column('z1_ceiling_power', sa.Float(), nullable=False),
    sa.Column('z3_target_power', sa.Float(), nullable=False),
    sa.Column('z3_budget_kj', sa.Float(), nullable=False),
    sa.Column('z4_ceiling_kj', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonemetrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('z1_time_sec', sa.Integer(), nullable=False),
    sa.Column('z1_avg_power', sa.Float(), nullable=False),
    sa.Column('z1_kj', sa.Float(), nullable=False),
    sa.Column('z2_time_sec', sa.Integer(), nullable=False),
    sa.Column('z2_avg_power', sa.Float(), nullable=False),
    sa.Column('z2_kj', sa.Float(), nullable=False),
    sa.Column('z3_time_sec', sa.Integer(), nullable=False),
    sa.Column('z3_avg_power', sa.Float(), nullable=False),
    sa.Column('z3_kj', sa.Float(), nullable=False),
    sa.Column('z4_time_sec', sa.Integer(), nullable=False),
    sa.Column('z4_avg_power', sa.Float(), nullable=False),
    sa.Column('z4_kj', sa.Float(), nullable=False),
    sa.Column('total_kj', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activitylog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zonemetrics')
    op.drop_table('weeklyplanner')
    op.drop_table('userphysiology')
    op.drop_table('endurancegoal')
    # ### end Alembic commands ###
