"""add activity multiplier

Revision ID: f41781e3913b
Revises: 202604280001
Create Date: 2026-04-30 16:31:13.705077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f41781e3913b'
down_revision: Union[str, None] = '202604280001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activity_multiplier', sa.Float(), nullable=False, server_default='1.2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activity_multiplier')
    # ### end Alembic commands ###
